### ISSUE TITLE
Character Control

### ISSUE THREAD

**Issue by sahlal** [Rokokoknik/jetSki-Game-Unity#6]
Implement character controls

**Comment by sahlal** [comment]
I know that you're working on it @Rokokoknik . How's it going?

**Comment by Rokokoknik** [comment]
Having some issues, will have something functional up late tonight. I
pushed something yesterday, but it failed.

Gerald R.

**Comment by Rokokoknik** [comment]
Basic script is up, will leave this open until I feel it is working as intended.

**Comment by Rokokoknik** [comment]
Bit behind, have a 4 hour block dedicated to working on this issue tonight (Monday November 30th), and a few others. Will be uploading some new scripts this evening.

**Comment by Rokokoknik** [comment]
Control script is as is for turn in, wont have time before midnight to implement better turning mechanics, along with everything else.
